### ISSUE TITLE
Publish docker image

### ISSUE THREAD

**Issue by JoshOrndorff** [Polkadot-Blockchain-Academy/Academy-PoW#18]
I believe CI builds a docker image now, right? We may as well publish it to help students who failed to compile it still participate in the activity. It might also help students who want to spin up more nodes in the cloud.

**Comment by fbielejec** [comment]
we could, but we'd have to pay for AWS ECR - have you seen the artifacts published from the workflows? 
E.g. https://github.com/Polkadot-Blockchain-Academy/Academy-PoW/actions/runs/5360095836

**Comment by JoshOrndorff** [comment]
I believe github will host the image for free for us :rocket: 

This is the CI job I set up for Tuxedo. It publishes two images to ghcr (github container registry) https://github.com/Off-Narrative-Labs/Tuxedo/blob/main/.github/workflows/docker.yml
