### ISSUE TITLE
Include fp_self_contained

### ISSUE THREAD

**Issue by notlesh** [Polkadot-Blockchain-Academy/Academy-PoW#35]
In #26 (and previously #9) the `fp_self_contained` extrinsic was not added, which will prevent Ethereum-style transactions from working correctly.

See:
* https://github.com/Polkadot-Blockchain-Academy/Academy-PoW/pull/26#issuecomment-1623824136
* https://paritytech.github.io/frontier/rustdocs/fp_self_contained/index.html
* https://github.com/paritytech/frontier/blob/3c75079ed627ec83db88ca78d2ea4d4da6b3d8af/template/runtime/src/lib.rs#L468

**Comment by JoshOrndorff** [comment]
I ended up solving this in the last few commits in #26
