### ISSUE TITLE
Bug: Error on build 

### ISSUE THREAD

**Issue by developeruche** [Polkadot-Blockchain-Academy/Academy-PoW#61]
error[E0308]: mismatched types
     --> /Users/user/Documents/projects/Academy-PoW/runtime/src/faucet.rs:32:40
      |
  32  |         #[pallet::weight((Weight::from(1_000_000), Pays::No))]
      |                           ------------ ^^^^^^^^^ expected `Weight`, found integer
      |                           |
      |                           arguments to this function are incorrect
      |
  note: associated function defined here
     --> /Users/user/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/convert/mod.rs:584:8
      |
  584 |     fn from(value: T) -> Self;
      |        ^^^^

  For more information about this error, try `rustc --explain E0308`.
  error: could not compile `academy-pow-runtime` (lib) due to previous error
  thread 'main' panicked at /Users/user/.cargo/git/checkouts/polkadot-sdk-cff69157b985ed76/789ffb6/substrate/utils/wasm-builder/src/wasm_project.rs:822:37:
  Copying the bloaty file to the project dir.: Os { code: 2, kind: NotFound, message: "No such file or directory" }
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by sepine** [comment]
The same issues I encountered

**Comment by JoshOrndorff** [comment]
Thanks for reporting. I reverted the mistake and will re-implement it properly in the future.
